SELECT RI.REST_ID, 
RI.REST_NAME AS REST_NAME, 
RI.FOOD_TYPE AS FOOD_TYPE,
RI.FAVORITES AS FAVORITES,
RI.ADDRESS AS ADDRESS, 
ROUND(AVG(RV.REVIEW_SCORE),2)AS SCORE
FROM REST_INFO AS RI 
INNER JOIN REST_REVIEW AS RV 
USING(REST_ID)
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;


-- 다른 풀이 

SELECT RI.REST_ID, 
RI.REST_NAME AS REST_NAME, 
RI.FOOD_TYPE AS FOOD_TYPE,
RI.FAVORITES AS FAVORITES,
RI.ADDRESS AS ADDRESS, 
ROUND(AVG(RV.REVIEW_SCORE),2)AS SCORE
FROM REST_INFO AS RI 
INNER JOIN REST_REVIEW AS RV 
USING(REST_ID)
GROUP BY RI.REST_ID
HAVING RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;