SELECT GEN3.ID AS ID
FROM ECOLI_DATA AS GEN3
WHERE GEN3.PARENT_ID IN (SELECT GEN2.ID
FROM ECOLI_DATA AS GEN2
WHERE GEN2.PARENT_ID IN (SELECT GEN1.ID
FROM ECOLI_DATA AS GEN1
WHERE GEN1.PARENT_ID IS NULL))
ORDER BY ID ;


-- join으로 풀기

SELECT GEN3.ID AS ID
FROM ECOLI_DATA AS GEN3
JOIN ECOLI_DATA AS GEN2
  ON GEN3.PARENT_ID = GEN2.ID
JOIN ECOLI_DATA AS GEN1
  ON GEN2.PARENT_ID = GEN1.ID AND GEN1.PARENT_ID IS NULL
ORDER BY ID;