SELECT YEAR(B.DIFFERENTIATION_DATE) AS YEAR, (ABS(B.SIZE_OF_COLONY - MAX_TABLE.SC)) AS YEAR_DEV,B.ID
FROM ECOLI_DATA AS B
JOIN (SELECT YEAR(A.DIFFERENTIATION_DATE) AS Y, MAX(A.SIZE_OF_COLONY) AS SC
     FROM ECOLI_DATA AS A
     GROUP BY YEAR(A.DIFFERENTIATION_DATE)) AS MAX_TABLE
ON YEAR(B.DIFFERENTIATION_DATE) = MAX_TABLE.Y
ORDER BY YEAR,YEAR_DEV;



--서브쿼리 별칭 필수 ( 조인시 필수 )

-- 연도별 대장균 크기의 편차
SELECT YEAR(A.DIFFERENTIATION_DATE) AS Y, MAX(A.SIZE_OF_COLONY) AS SC
     FROM ECOLI_DATA AS A
     GROUP BY YEAR(A.DIFFERENTIATION_DATE)

-- 연도별로 대장균 크기의 편차를 구해야함.
ON YEAR(B.DIFFERENTIATION_DATE) = MAX_TABLE.Y

-- 편차
(ABS(B.SIZE_OF_COLONY - MAX_TABLE.SC)) AS YEAR_DEV
-- ABS 음수 방지 절댓값 함수