-- # CONCAT(합치고 싶은열 , '합치고 싶은 말' ) -> 집계 함수 , SUBSTRING, SUBSTR 사용 가능
-- # SUBSTRING(자르고싶은열, 시작하는 인덱스, 시작하는 곳에서 부터 몇 번째 인덱스까지 할지)
-- # GROUP BY

SELECT CONCAT(NAME, '(' , SUBSTRING(OCCUPATION, 1, 1) , ')' ) AS RESULT
FROM OCCUPATIONS
ORDER BY NAME ASC;

SELECT CONCAT('There are a total of ', COUNT(OCCUPATION),' ', LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION) ASC, LOWER(OCCUPATION) ASC;