SELECT 
    C.CAR_ID AS CAR_ID,
    C.CAR_TYPE AS CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON 
    C.CAR_ID = H.CAR_ID
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON 
    C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_ID NOT IN (
        SELECT SH.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS SH
        WHERE SH.START_DATE <= '2022-11-30' AND SH.END_DATE >= '2022-11-01'
    )
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
GROUP BY 
    C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, P.DISCOUNT_RATE
HAVING
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE)/ 100) BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC
