SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND MONTH(DATE_OF_BIRTH) = 03 AND GENDER ='W'
ORDER BY MEMBER_ID ASC;



-- SELECT MEMBER_ID, 
--        MEMBER_NAME, 
--        GENDER, 
--        DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d %H:%i:%s') AS FORMATTED_DATE_OF_BIRTH
-- FROM MEMBER_PROFILE
-- WHERE TLNO IS NOT NULL 
--   AND YEAR(DATE_OF_BIRTH) = 1992
--   AND MONTH(DATE_OF_BIRTH) = 2
--   AND DAY(DATE_OF_BIRTH) = 12
--   AND HOUR(DATE_OF_BIRTH) = 10
--   AND MINUTE(DATE_OF_BIRTH) = 30
--   AND SECOND(DATE_OF_BIRTH) = 0 
--   AND GENDER = 'W'
-- ORDER BY MEMBER_ID ASC;