SELECT UGB.TITLE AS TITLE , 
UGB.BOARD_ID AS BOARD_ID,
UGR.REPLY_ID AS REPLY_ID,
UGR.WRITER_ID AS WRITER_ID,
UGR.CONTENTS AS CONTENTS,
DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB 
JOIN USED_GOODS_REPLY AS UGR
ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE YEAR(UGB.CREATED_DATE) = 2022 AND MONTH(UGB.CREATED_DATE) = 10
ORDER BY UGR.CREATED_DATE ASC , UGB.TITLE ASC;