WITH RANK_DATA AS(
SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
FROM ECOLI_DATA)

SELECT ID, (CASE 
            WHEN SIZE_RANK <= 0.25 THEN 'CRITICAL'
            WHEN SIZE_RANK <= 0.5 THEN 'HIGH'
            WHEN SIZE_RANK <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
            END) AS COLONY_NAME
FROM RANK_DATA
ORDER BY ID

--다른 풀이

SELECT A.ID, (CASE
            WHEN A.SIZE_RANK <= 0.25 THEN 'CRITICAL'
            WHEN A.SIZE_RANK <= 0.5 THEN 'HIGH'
            WHEN A.SIZE_RANK <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
            END) AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
        FROM ECOLI_DATA) AS A
ORDER BY ID;


