SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C
JOIN ECOLI_DATA AS P
ON C.PARENT_ID = P.ID
WHERE C.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY C.ID;


SELECT *
FROM ECOLI_DATA AS P
JOIN ECOLI_DATA AS C
ON P.ID = C.PARENT_ID;

-- 부모의 ID가 자식의 부모_ID에 있는것만 나오는것.