SELECT CATEGORY, PRICE AS MAX_PRICE ,PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY,PRICE) IN (SELECT CATEGORY,MAX(PRICE)
                          FROM FOOD_PRODUCT
                          WHERE CATEGORY IN ('식용유','김치','국','과자')
                          GROUP BY CATEGORY)
GROUP BY CATEGORY,PRODUCT_NAME
ORDER BY MAX_PRICE DESC