SELECT B.AUTHOR_ID AS AUTHOR_ID, 
A.AUTHOR_NAME AS AUTHOR_NAME,
B.CATEGORY AS CATEGORY,
(SUM(B.PRICE * BS.SALES)) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;