SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (REST_ID,FAVORITES) IN (SELECT REST_ID, MAX(FAVORITES)
                  FROM REST_INFO
                  GROUP BY REST_ID)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;

-- ID값은 고유해서 그룹화해도 의미가 없다.
-- GROUP BY FOOD_TYPE이 사용되지만 REST_ID 서브쿼리 결과가 연관이 없어서 결과가 옳바르지 않음.


SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
                  FROM REST_INFO
                  GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;

-- 각 음식 유형별로 가장 즐겨찾기 수가 많은 것을 그룹화한다.
