SELECT FH.FLAVOR AS FLAVOR
FROM FIRST_HALF AS FH
JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER) AS AMOUNT
FROM JULY
GROUP BY FLAVOR) AS J
ON FH.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY FH.TOTAL_ORDER + J.AMOUNT DESC
LIMIT 3;